# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  # orgs contain basc recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@2.0
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
  browser: circleci/browser-tools@1.2.4

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build-deploy:
    docker:
      # the base image can run most needed actions with orbs
      - image: 'cimg/base:stable'
    steps:
      - node/install:
          node-version: '14.15.1'
      - checkout
      # setup aws cli
      - aws-cli/setup
      # setup eb cli
      - aws-elastic-beanstalk/setup
      # install chrome
      - browser/install-chrome
      # install dependencies in both apps
      - run:
          name: Install frontend dependencies
          command: |
            npm run frontend:install
      - run:
          name: Install backend dependencies
          command: |
            npm run backend:install
      # run frontend tests
      - run:
          name: Run frontend tests
          command: |
            npm run frontend:test
      # build & deploy both apps
      - run:
          name: Deploy frontend
          command: |
            npm run frontend:deploy
      - run:
          name: Deploy backend
          command: |
            npm run backend:deploy
workflows:
  main:                    # workflow label
    jobs:
      - build-deploy:  
          filters:
            branches:
               only:                
                  - master

