# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  # orgs contain basc recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@2.0
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    docker:
      # the base image can run most needed actions with orbs
      - image: 'cimg/base:stable'
    steps:
      - node/install
      - checkout
      # setup aws cli
      - aws-cli/setup
      # setup eb cli
      - aws-elastic-beanstalk/setup
      # install dependencies in both apps
      - run:
          name: install frontend dependencies
          command: |
            npm run frontend:install
      - run:
          name: install backend dependencies
          command: |
            npm run backend:install
      # build & deploy both apps
      - run:
          name: deploy frontend
          command: |
            npm run frontend:deploy
      - run:
          name: deploy backend
          command: |
            npm run backend:deploy
